#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

"""
Main script, interface to read and write various chatlog file formats.
"""

import optparse
import json
import sys

import chatlogparser
import chatlogwriter

__docformat__ = "restructuredtext en"

def main():
    options, args = _parse_args()

    filename = args[0]

    imported = chatlogparser.parse(filename, options.read_format)

    if options.outfile is not None:
        outfile = open(options.outfile, "w")
    else:
        outfile = sys.stdout

    chatlogwriter.write(imported, outfile, options.write_format)

    if options.outfile is not None:
        outfile.close()


def _parse_args():
    """
    Parses the command line arguments.

    :return: Tuple with options and (positional) arguments.
    :rtype: tuple
    """
    parser = optparse.OptionParser(usage="%prog [options] logfile", description="Parses chatlogs and writes them in other formats.")
    parser.add_option("-o", dest="outfile", default=None, help="File to write to")
    parser.add_option("-w", dest="write_format", default="pidgin", help="Write format. [default: %default]")
    parser.add_option("-r", dest="read_format", default="adium", help="Read format. [default: %default]")

    return parser.parse_args()


if __name__ == "__main__":
    main()
